# Generated by Django 4.0.1 on 2022-09-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Manager_id', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
